
-- Remove sequence-based defaults since booking codes will be generated by edge function
-- based on current year+month prefix
ALTER TABLE public.bookings ALTER COLUMN booking_code DROP DEFAULT;
ALTER TABLE public.invoices ALTER COLUMN invoice_number DROP DEFAULT;
